version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-short-url

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data: /data/db"
    networks:
      - app-short-url

volumes:
  mongo-data:

networks:
  app-short-url:
    driver: brigde
